services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inceptions
    env_file:
      - .env
    restart: on-failure

  wordpress:
    depends_on:  # Ajoutez cette section
      - mariadb
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    ports:
      - 9000:9000
    networks:
      - inceptions
    restart: on-failure

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/najeuneh/Desktop/docker/mariadb
      o: bind

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/najeuneh/Desktop/docker/wordpress
      o: bind

networks:
  inceptions:
